version: '3'
services:
  xwaf:
    build:
      context: ./config
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    networks:
      - mynetwork  
    volumes:
      - ./modsec:/var/log/modsec
  pyweb:
    build:
      context: ./flask
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge